// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.2
// source: apps/message/pb/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// 获取消息列表
	ChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error)
	// 消息操作
	ChatMessageAction(ctx context.Context, in *ChatMessageActionRequest, opts ...grpc.CallOption) (*ChatMessageActionResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) ChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error) {
	out := new(ChatMessageListResponse)
	err := c.cc.Invoke(ctx, "/dousheng.message.Service/ChatMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ChatMessageAction(ctx context.Context, in *ChatMessageActionRequest, opts ...grpc.CallOption) (*ChatMessageActionResponse, error) {
	out := new(ChatMessageActionResponse)
	err := c.cc.Invoke(ctx, "/dousheng.message.Service/ChatMessageAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// 获取消息列表
	ChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error)
	// 消息操作
	ChatMessageAction(context.Context, *ChatMessageActionRequest) (*ChatMessageActionResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) ChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatMessageList not implemented")
}
func (UnimplementedServiceServer) ChatMessageAction(context.Context, *ChatMessageActionRequest) (*ChatMessageActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatMessageAction not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_ChatMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ChatMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dousheng.message.Service/ChatMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ChatMessageList(ctx, req.(*ChatMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ChatMessageAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ChatMessageAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dousheng.message.Service/ChatMessageAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ChatMessageAction(ctx, req.(*ChatMessageActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dousheng.message.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatMessageList",
			Handler:    _Service_ChatMessageList_Handler,
		},
		{
			MethodName: "ChatMessageAction",
			Handler:    _Service_ChatMessageAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/message/pb/message.proto",
}
