# Author: BeYoung
# Date: 2023/1/26 3:13
# Software: GoLand

snowflakeID: 1

sql:
  driver: mysql
  host: 124.222.189.27
  post: 3306
  username: root
  password: 2194150786@qq.com
  database: go_to_byte
  charset: utf8mb3