// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID      int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	VideoID int64  `gorm:"column:video_id;type:bigint;not null" json:"video_id"`
	UserID  int64  `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	Content string `gorm:"column:content;type:varchar(128);not null" json:"content"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
