// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	Follow   int64 `gorm:"column:follow;type:bigint;primaryKey" json:"follow"`
	ToFollow int64 `gorm:"column:to_follow;type:bigint;primaryKey" json:"to_follow"`
	Flag     int64 `gorm:"column:flag;type:tinyint(1);not null" json:"flag"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
