// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollower = "follower"

// Follower mapped from table <follower>
type Follower struct {
	Follower   int64 `gorm:"column:follower;type:bigint;primaryKey" json:"follower"`
	ToFollower int64 `gorm:"column:to_follower;type:bigint;primaryKey" json:"to_follower"`
	Flag       int64 `gorm:"column:flag;type:tinyint(1);not null" json:"flag"`
}

// TableName Follower's table name
func (*Follower) TableName() string {
	return TableNameFollower
}
