// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserInfo = "user_info"

// UserInfo mapped from table <user_info>
type UserInfo struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Username string `gorm:"column:username;type:varchar(16);not null" json:"username"`
	Passwd   string `gorm:"column:passwd;type:char(128);not null" json:"passwd"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
