// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFollow = "user_follow"

// UserFollow mapped from table <user_follow>
type UserFollow struct {
	FollowId1  int64 `gorm:"column:follow_id1;type:bigint;primaryKey" json:"follow_id1"`
	FollowId2  int64 `gorm:"column:follow_id2;type:bigint;primaryKey" json:"follow_id2"`
	FollowFlag int64 `gorm:"column:follow_flag;type:tinyint(1);not null" json:"follow_flag"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
