// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoComment = "video_comment"

// VideoComment mapped from table <video_comment>
type VideoComment struct {
	CommentID    int64  `gorm:"column:comment_id;type:bigint;primaryKey" json:"comment_id"`
	CommentVideo int64  `gorm:"column:comment_video;type:bigint;not null" json:"comment_video"`
	CommentUser  int64  `gorm:"column:comment_user;type:bigint;not null" json:"comment_user"`
	Comment      string `gorm:"column:comment;type:varchar(128);not null" json:"comment"`
}

// TableName VideoComment's table name
func (*VideoComment) TableName() string {
	return TableNameVideoComment
}
