// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserID   int64  `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ToUserID int64  `gorm:"column:to_user_id;type:bigint;not null" json:"to_user_id"`
	Content  string `gorm:"column:content;type:varchar(128);not null" json:"content"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
