// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "relation"

// Relation mapped from table <relation>
type Relation struct {
	ID       int64 `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserID   int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ToUserID int64 `gorm:"column:to_user_id;type:bigint;not null" json:"to_user_id"`
	Flag     int64 `gorm:"column:flag;type:tinyint(1);not null" json:"flag"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
