// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "favorite"

// Favorite mapped from table <favorite>
type Favorite struct {
	ID      int64 `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserID  int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	VideoID int64 `gorm:"column:video_id;type:bigint;not null" json:"video_id"`
	Flag    int64 `gorm:"column:flag;type:tinyint(1);not null" json:"flag"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
