// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	AuthID   int64  `gorm:"column:auth_id;type:bigint;not null" json:"auth_id"`
	Titel    string `gorm:"column:titel;type:varchar(128);not null" json:"titel"`
	CoverURL string `gorm:"column:cover_url;type:longtext;not null" json:"cover_url"`
	PlayURL  string `gorm:"column:play_url;type:varchar(256);not null" json:"play_url"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
