// Author: BeYoung
// Date: 2023/2/24 20:56
// Software: GoLand

package utils

import (
	"context"
	"errors"
	"github.com/bwmarrin/snowflake"
	"go.uber.org/zap"
)

// IDGen generates a snowflake node, id is generated by node
// if you want to generate a new id, use IDgen.Generate()
type IDGen struct {
	*snowflake.Node
}

// NewIDGen returns a new IDGen
func NewIDGen(localID int) (gen IDGen, err error) {
	gen.Node, err = snowflake.NewNode(int64(localID))
	if err != nil || gen.Node == nil {
		zap.S().Errorf("New snowflake node error: %v", err)
	}
	return
}

// GetID NewID returns
func GetID(ctx *context.Context) (id snowflake.ID, err error) {
	if ctx == nil {
		return 0, errors.New("context is nil")
	}
	idGen := (*ctx).Value("idGen")
	id = idGen.(IDGen).Generate()
	return id, nil
}
